### ISSUE TITLE
High correlation between covariate(s) and treatment detected

### ISSUE THREAD

**Issue by scottduvall** [ohdsi-studies/Covid19EstimationHydroxychloroquine#1]
<img width="1329" alt="Screen Shot 2020-03-29 at 3 06 32 PM" src="https://user-images.githubusercontent.com/62856435/77861173-9f6bcd80-71d0-11ea-84e6-c13b984add6d.png">

**Comment by jamieweaver** [comment]
clavulanate (because if its use in combination with amoxicillin) and other covariates that act as proxies for exposure cohort membership have been removed from the set of input covariates for the PS model
