### ISSUE TITLE
object 'cohortMethodResult' not found

### ISSUE THREAD

**Issue by PRijnbeek** [ohdsi-studies/Covid19EstimationHydroxychloroquine#3]
I have run this on IPCI . I receive this error: Error in unique(cohortMethodResult[, c("targetId", "comparatorId", "outcomeId")]) : 
object 'cohortMethodResult' not found. 

Not clear what the problem is.

**Comment by jamieweaver** [comment]
bug fixed in global.r file in the shiny application
